### ISSUE TITLE
Missing support for new .NET 6 Date & Time classes

### ISSUE THREAD

**Issue by Chimaine** [Chips100/clr2ts#10]
When trying to use the new .NET 6 types like System.DateOnly or System.TimeOnly, clr2ts outputs 

> System.NotSupportedException: No strategy to translate definition of type System.DateOnly

See [Date, Time, and Time Zone Enhancements in .NET 6](https://devblogs.microsoft.com/dotnet/date-time-and-time-zone-enhancements-in-net-6/).

Might be worth having a .NET 6 target that supports these types in `BuiltInTypeTranslationStrategy`.

**Comment by Chips100** [comment]
Out-of-the-box Support for *DateOnly* and *TimeOnly* has been added in version 0.5.1.
By default, *DateOnly* will be translated to the TypeScript *Date*-type, as it is serialized to a string that can be parsed by `new Date()`, just as *DateTime*. *TimeOnly* will be translated to *string* though, as there is no suitable type in vanilla TypeScript.

As always, the behaviour can be overridden by a *custom type map* in the config, for example:

```
  "transpilation": {
    "customTypeMaps": [
      {
        "type": "System.DateOnly",
        "name": "MyDateOnlyType",
        "source": "@somelibrary/dateonly"
      },
      {
        "type": "System.TimeOnly",
        "name": "any"
      }
    ],
```
