### ISSUE TITLE
Missing support for Dictionary / Issue translation

### ISSUE THREAD

**Issue by Bissel** [Chips100/clr2ts#12]
`Dictionary<string, string> Data { get; set; }`
Is translated to
`public data: {[key: string]: string } = new {[key: string]: string }();`
Type-Script don't like that (the `new {[key: string]: string }()` part)

Is there a reason to instantiate the value? if it is not set it works.

**Comment by Bissel** [comment]
Possible Workaround is to use a WrapperClass and a List e.g.:

```
class Wrapper { 
  public string Key { get; set; }
  public string Value { get; set; }
}
```
`List<Wrapper> Data { get; set; }`

**Comment by rehli** [comment]
Hey, i had the same Problem. For me the Solution was to use **I**Dictionary<string, string> instead of the concrete Type. With the Interface it is initialised with null.

**Comment by Bissel** [comment]
Thanks for the reply, Interfaces of Lists and Dictionarys is the correct usage
